# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/old/'
            - '../src/Application/Product/Dto/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\Service\Product\ProductStockManagerInterface: '@App\Service\Product\ProductStockManager'

    FOS\ElasticaBundle\Finder\FinderInterface $orderFinder: '@fos_elastica.finder.orders'
    FOS\ElasticaBundle\Persister\ObjectPersisterInterface $orderPersister: '@fos_elastica.object_persister.orders'

    App\Service\ElasticsearchOrderService:
      arguments:
        $orderPersister: '@fos_elastica.object_persister.orders'
